# Generated by Django 4.0.4 on 2022-05-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': '답변',
            },
        ),
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('message', models.IntegerField(verbose_name='메세지')),
                ('is_phone', models.BooleanField(default=False, verbose_name='핸드폰 수신')),
                ('is_email', models.BooleanField(default=False, verbose_name='이메일 수신')),
                ('email', models.EmailField(max_length=100, verbose_name='이메일')),
                ('status', models.CharField(choices=[('문의등록', '문의등록'), ('접수완료', '접수완료'), ('답변완료', '답변완료')], default='문의등록', max_length=12, verbose_name='상태')),
                ('category', models.CharField(choices=[('일반', '일반'), ('계정', '계정'), ('기타', '기타')], default='일반', max_length=12, verbose_name='카테고리')),
                ('comment', models.ManyToManyField(blank=True, related_name='QnA', to='posts.comment', verbose_name='댓글')),
            ],
            options={
                'verbose_name_plural': '문의사항',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contents', models.TextField(verbose_name='내용')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('category', models.CharField(choices=[('일반', '일반'), ('계정', '계정'), ('기타', '기타')], default='일반', max_length=12, verbose_name='카테고리')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='FAQ', to='posts.comment', verbose_name='댓글')),
            ],
            options={
                'verbose_name_plural': '자주묻는질문',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='qna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='posts.qna', verbose_name='게시글'),
        ),
    ]
