# Generated by Django 4.0.4 on 2022-04-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='message',
            field=models.IntegerField(),
        ),
    ]
