# Generated by Django 4.0.4 on 2022-05-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='is_email',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='이메일 수신'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='is_phone',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='핸드폰 수신'),
        ),
    ]
