# Generated by Django 4.0.4 on 2022-04-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_qna_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='content',
            new_name='contents',
        ),
        migrations.AlterField(
            model_name='qna',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='QnA', to='posts.comment', verbose_name='댓글'),
        ),
        migrations.AddField(
            model_name='qna',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='QnA', to='posts.categories', verbose_name='카테고리'),
        ),
    ]
