# Generated by Django 4.0.4 on 2022-05-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_qna_is_email_alter_qna_is_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='message',
            field=models.IntegerField(verbose_name='번호'),
        ),
    ]
