# Generated by Django 4.0.4 on 2022-04-20 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_qna_options_alter_qna_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='qna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='posts.qna', verbose_name='게시글'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='QnA', to='posts.comment', verbose_name='댓글'),
        ),
    ]
