# Generated by Django 4.0.4 on 2022-05-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '남자'), ('female', '여자'), ('other', '그 외')], max_length=10, verbose_name='gender'),
        ),
    ]
